alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: oysloe.com
  type: PRIMARY
  zone: oysloe.com
- domain: www.oysloe.com
  type: ALIAS
  zone: oysloe.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: oysloe-webappbyedmund
    match:
      authority: {}
      path:
        prefix: /
name: oysloe
region: fra
static_sites:
- catchall_document: index.html
  environment_slug: node-js
  build_command: npm run build
  envs:
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: https://api.oysloe.com/api-v1
  - key: VITE_WS_URL
    scope: BUILD_TIME
    value: wss://api.oysloe.com/ws
  - key: VITE_API_CREDENTIALS
    scope: BUILD_TIME
    value: omit
  - key: VITE_API_AUTH_SCHEME
    scope: BUILD_TIME
    value: Token
  - key: VITE_USE_MOCKS
    scope: BUILD_TIME
    value: "false"
  - key: VITE_MEDIA_URL
    scope: BUILD_TIME
    value: https://api.oysloe.com
  - key: VITE_FIREBASE_API_KEY
    scope: BUILD_TIME
    value: AIzaSyBxeua-AU_WOpNS2ECM4owYxbOTFoKDFOA
  - key: VITE_FIREBASE_AUTH_DOMAIN
    scope: BUILD_TIME
    value: oysloe-45292.firebaseapp.com
  - key: VITE_FIREBASE_PROJECT_ID
    scope: BUILD_TIME
    value: oysloe-45292
  - key: VITE_FIREBASE_STORAGE_BUCKET
    scope: BUILD_TIME
    value: oysloe-45292.firebasestorage.app
  - key: VITE_FIREBASE_MESSAGING_SENDER_ID
    scope: BUILD_TIME
    value: "473482750146"
  - key: VITE_FIREBASE_APP_ID
    scope: BUILD_TIME
    value: 1:473482750146:web:070c9347e8964a7003f35b
  - key: VITE_FIREBASE_MEASUREMENT_ID
    scope: BUILD_TIME
    value: G-MVPHXFTGWD
  - key: VITE_FIREBASE_VAPID_KEY
    scope: BUILD_TIME
    value: BLVZZeWKBodftfYErb5CLwYddVGcTT8u7tQ9ot38UIZg-OXtED1B1s2l5HoF9cb8r1vHW7ybox7mDb6vXXdIrtk
  github:
    branch: main
    deploy_on_push: true
    repo: danielagblo/oysloe-webappbyedmund
  name: oysloe-webappbyedmund
  source_dir: /
